name: Build APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - run: npm install
      - run: npm run build
      - run: npx cap add android
      - run: sed -i '/<manifest/a\    <uses-permission android:name="android.permission.RECORD_AUDIO" />' android/app/src/main/AndroidManifest.xml
      - run: cd android && ./gradlew assembleDebug
      
      - uses: actions/upload-artifact@v4
        with:
          name: APK
          path: android/app/build/outputs/apk/debug/*.apk